# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f112f6d6a791e33e8addf4987df87950c721b1bccb9e8d0f280a390076603f02830c9228d87bac458bd5ed3346abbefe42fab335a1b7d712d10681b900c1f8

test:
  secret_key_base: 4ffad1fc1d07061dc8f5344f6d313172c7aad7c9e395eeb91af4b8d7aa2b6b5bb973979613db6de4971d497893176fa35b2f915d697232ff5f059c6dad34cc64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
